<?php
	// This data is generated by REST API for each <tr>
	$available_states_1 = array('AL', 'AK');
	$available_states_2 = array('AZ', 'AR');
	$available_states_3 = array('CA', 'CO');

	wp_store(
		array(
			'state' => array(
				'interactivity' => array(
					'currentRegionCode' => 'AK',
				),
			),
		)
	);
?>

<div
	<?php echo get_block_wrapper_attributes(); ?> 
	data-wp-interactive
	>

	<!-- 
			My goal is to make functionality based onChange (value must equals to currentRegionCode) to show and hide elements on specyfic <tr>
	-->
	<select data-wp-on--change="actions.interactivity.onChange" class="select">
		<option value="">Select state</option>
		<option value="AL">Alabama</option>
		<option value="AK">Alaska</option>
		<option value="AZ">Arizona</option>
		<option value="AR">Arkansas</option>
		<option value="CA">California</option>
		<option value="CO">Colorado</option>
		<option value="MI">Michigan</option>
		<option value="other">Other state</option>
	</select>

	<table style="width:100%">
			<!-- this <tr> is generated by loop based on API response -->
		<tr
			data-wp-context='{ "interactivity": { "availableStates": <?php echo htmlentities( wp_json_encode( $available_states_1 ) ); ?>} }'
			data-wp-bind--hidden="!selectors.interactivity.isShown"
		>
			<td>Alfreds Futterkiste</td>
			<td>Maria Anders</td>
			<td>
				Germany
			</td>
		</tr>
		<tr
			data-wp-context='{ "interactivity": { "availableStates": <?php echo htmlentities( wp_json_encode( $available_states_2 ) ); ?>} }'
			data-wp-bind--hidden="!selectors.interactivity.isShown"
		>
			<td>Centro comercial Moctezuma</td>
			<td>Francisco Chang</td>
			<td>Mexico</td>
		</tr>
		<tr
			data-wp-context='{ "interactivity": { "availableStates": <?php echo htmlentities( wp_json_encode( $available_states_3 ) ); ?>} }'
			data-wp-bind--hidden="!selectors.interactivity.isShown"
		>
			<td>Ernst Handel</td>
			<td>Roland Mendel</td>
			<td>Austria</td>
		</tr>
	</table>
</div>
